### PR TITLE
chore(ng-intl-input): upgrade to 12.1.6

### LINKED ISSUE #90: Canadian Phone Format is obsolete
The formatting of Canadian phone numbers is obsolete. It uses a (999) 999-9999 format, but I live in Canada and we no longer use this format since many years. The correct format would be 999 999-9999 (without parentheses).

Even the canadian government website says the format with parentheses is obsolete. See [this page](http://www.btb.termiumplus.gc.ca/tpv2guides/guides/favart/index-eng.html?lang=eng&lettr=indx_autr8SPbfCcS_FFE&page=9N6fM9QmOwCE.html#zz8SPbfCcS_FFE).

Relevant text in webpage:

> Canadian telephone numbers are written NXX NXX-XXXX and can be preceded by 1 or +1. A hyphen should separate the three-digit and four-digit blocks of the local number but otherwise spaces are used. **Parentheses around the area code (NXX) may still be used but are becoming obsolete**.

**EDIT**
Since the webpage has been last updated in 2002, I think it is time to make the move and remove the parentheses.

### LINKED ISSUE #103: starting with 7 series indian mobile no not accepted
7020xxxxxx series indian mobile no not accepted by this input, its return undefined. Please fix this problem. Thank you

### LINKED ISSUE #108: +14632214194 is treated as non-valid number
hello, +14632214194 is treated as non-valid number. please verify.

### LINKED ISSUE #111: Add new phone operator code
hi there,
can u add a new phone operator code for Kyrgyzstan.
new code 50
+996 50X XXX XXX

### PR DESCRIPTION
**Pull request by jrthib**
Resolves #108, Resolves #103, Resolves #90, Resolves #111

refactor(index): use node module dependencies

### CODE REVIEW

**Comment by jrthib** [comment]
@bighappyface Not sure why the selenium stuff is failing. Never have seen this error before. Do you have any ideas that I can try?

**Comment by bighappyface** [comment]
Try updating all of the dependencies in package.json

**Comment by jrthib** [comment]
I got nothing man. I'm seeing bugs with selenium / webdriver reported, but the workarounds don't work. Also the versions they say have it "fixed" don't seem to help either.

**Comment by SyntaxStacks** [comment]
@jrthib FIRST OFF THANK YOU FOR YOUR CONTRIBUTION! 

I notices that the error is related to phantomjs and when looking through their issues I found this.
https://github.com/Medium/phantomjs/issues/765

I'll continue to debug on my side to see if i can resolve the issue

**Comment by jrthib** [comment]
No problem! Let me know if you need me to squash the commits. This PR will really help international phone number validations.

**Comment by pbrain19** [comment]
Happy new year everyone. Any update on this?

**Pull request merged**
