### PR TITLE
feat(directive): add support for tel input fields

### PR DESCRIPTION
**Pull request by gergderkson**

### CODE REVIEW

**Comment by bighappyface** [comment]
@gergderksons awesome! Thanks for the contribution.

Please strip out the changes in `dist` as we will update it when we bump the version after accepting this PR. Cool?

**Comment by gergderkson** [comment]
@bighappyface done :smile:

**Comment by bighappyface** [comment]
@gergderkson sorry to nitpick, but would you remove the permission changes on those files as well? We don't need that tracked under version control and you can avoid that stuff by running `git config core.filemode false`

**Comment by gergderkson** [comment]
@bighappyface My bad. That's it fixed.  Cheers for the pointer!

**Comment by bighappyface** [comment]
+1

**Comment by shenlong** [comment]
Hi @gergderkson, thanks for adding the test cases! Woot! input type="tel" support!

**Pull request merged**
