### PR TITLE
fix(directive): full phone number with dial code now evaluates to a string rather than boolean

### PR DESCRIPTION
**Pull request by jrthib**

### CODE REVIEW

**Comment by bighappyface** [comment]
@jrthib thanks for the speedy refinements. While I didn't did the GitHub PR numbers in the test descriptions, I did like something distinguishing the test from the previous. Perhaps adding "and has a plus sign" to the end of the new test cases (e.g. `should set the country when model value is present and has a plus sign`) will do it?

**Comment by jrthib** [comment]
Sure, separate commit or should I squash it again?

**Comment by bighappyface** [comment]
Try making the changes and amending the commit. It will have the same commit message and other changes, but result in a new commit hash. You can just force-push this new commit to your fork and this PR will pick it up automatically.

**Comment by jrthib** [comment]
@bighappyface All set!

**Comment by bighappyface** [comment]
+1

@SyntaxStacks may we have your review too?

**Comment by jrthib** [comment]
Do you know when this might be merged and released? I'm currently using it in a feature I'm developing and am hoping that when we roll out we can just use the updated version of the plugin instead of a git commit reference.

**Comment by SyntaxStacks** [comment]
@jrthib thanks for the contribution!

**Comment by jrthib** [comment]
No prob!

**Comment by SyntaxStacks** [comment]
@jrthib https://github.com/hodgepodgers/ng-intl-tel-input/tree/v1.2.1 

that release includes your changes, and a validation fix https://github.com/hodgepodgers/ng-intl-tel-input/pull/34

**Pull request merged**
