### PR TITLE
fixes for issue #98

### PR DESCRIPTION
**Pull request by berserk81**
The changes includes:
- Fixes for issue #98: triggering a `change` event in `handleCountryChange` method to notify the angular model controller, this causes the model value to be updated when only the country is changed.
- Changing the listening behavior of `countrychange` event, if there are more than one phone inputs, listening to `countrychange` on the `$window` will trigger the function on all inputs, listening the event just on the directive element fixes this.

### CODE REVIEW

**Comment by bighappyface** [comment]
@berserk81 thanks for the PR.

* Please read the contributing document - https://github.com/hodgepodgers/ng-intl-tel-input/blob/5f0ca7dbb2b954249b176945fd61bc252d8a5ec6/CONTRIBUTING.md
* Please revert all changes to the `dist` directory. Changes to that directory are made as part of a release
* Please reduce the amount of unnecessary, issue-specific comments in this PR

**Comment by bighappyface** [comment]
@berserk81 thanks for the quick turnaround.

Next steps:

* Squash commits into a single commit
* Per the contributing guide please use conventional changelog commit message format
* Implement some testing around these changes. While no regression has occurred with the modifications, there are no new tests demonstrating or describing the intended improvements

**Comment by berserk81** [comment]
How can I squash commits into a single commit? I mean for the already
pushed commits?

**Comment by bighappyface** [comment]
@berserk81 this is a good opportunity for you to search the web for guidance on rebasing and squashing.

Here is a link to help you out - https://www.google.com/search?q=github+squash+all+commits

**Pull request closed without merging**
