### PR TITLE
Add support for input type="tel"

### PR DESCRIPTION
**Pull request by shenlong**
This will open the keypad for mobile devices instead of the full keyboard.

### CODE REVIEW

**Comment by bighappyface** [comment]
@shenlong thanks for adding additional input type support!

A few things:

1. Please refer to CONTRIBUTING.md for guidance on contributing
2. Please squash your commits down to one
3. Please reword your single commit message to follow the conventional changelog format (see commit history for examples)
4. Please add a test demonstrating the functionality with the `type` attribute set to "tel" in ng-intl-tel-input.directive.spec.js

**Comment by bighappyface** [comment]
@shenlong any movement on this?

**Comment by shenlong** [comment]
@bighappyface hi, i am not familiar with test case. Will need to take a look. Kinda busy with work... if someone can help me, will be great!

**Comment by bighappyface** [comment]
Closed with #51

**Pull request closed without merging**
