### PR TITLE
fix(bower): update main path for wiredep integration

### PR DESCRIPTION
**Pull request by vogloblinsky**

### CODE REVIEW

**Comment by bighappyface** [comment]
@vogloblinsky thanks for the PR!

One more thing: please use the conventional changelog commit message format per our [CONTRIBUTING](https://github.com/hodgepodgers/ng-intl-tel-input/blob/4c4c8106f0b6cb7257253ffe558ba4751cd2afa5/CONTRIBUTING.md) guidelines.

My recommendation is `fix(bower): update main path for wiredep integration`

Once the commit message is good I'll merge.

**Comment by vogloblinsky** [comment]
Done

**Comment by bighappyface** [comment]
@vogloblinsky close, but no cigar. You'll need to amend the commit message, not the PR title.

**Comment by SyntaxStacks** [comment]
@vogloblinsky please change the commit message with `git commit --amend`

click [here](https://github.com/hodgepodgers/ng-intl-tel-input/blob/master/CONTRIBUTING.md) for more info on contributing.

**Comment by SyntaxStacks** [comment]
and thank you for your input!

**Comment by vogloblinsky** [comment]
Done

**Pull request merged**
